language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

script:
    - mkdir -p build/logs
    - vendor/kpacha/travis-phpqa/bin/phpqa -v
